---
- name: Setup Django App and Virtual Environment on Remote Server
  hosts: lxc
  vars_files:
    - vars.yml
  tasks:

    # Installs these three packages. Doesn't if they already exist.
    - name: Ensure Python3, pip, and virtualenv are installed
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present
        update_cache: yes
      become: true

    # Clones the project from GitHub
    - name: Clone project repository from Git
      git:
        repo: "{{ repo_url }}"  # URL of the GitHub repository defined in vars.yml
        dest: "{{ project_dir }}"  # Directory where the repo will be cloned
        single_branch: yes
        version: master
        update: yes  # Update the repo if it already exists

    # creates venv. Doesn't if it already exists
    - name: Create virtual environment
      command: python3 -m venv {{ venv_dir }}
      args:
        creates: "{{ venv_dir }}"  # This ensures the command is only run if the venv doesn't already exist

    - name: Install Python packages from requirements.txt in the virtual environment
      pip:
        requirements: "{{ requirements_file }}"
        virtualenv: "{{ venv_dir }}"

