---
- name: Remove systemd service and socket units
  # hosts: localhost
  become: true
  gather_facts: false
  vars_files:
    - vars.yml

  tasks:
    - name: Remove socket unit file
      file:
        path: /etc/systemd/system/{{ service_name }}.socket
        state: absent

    - name: Remove service unit file
      file:
        path: /etc/systemd/system/{{ service_name }}.service
        state: absent

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: yes
